on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip Forge MDK
        run: unzip forge-1.16.5-36.2.42-mdk.zip

      - name: Enter project and build
        run: |
          cd forge-1.16.5-36.2.42-mdk
          chmod +x gradlew
          ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: PeasifulVanilla
          path: forge-1.16.5-36.2.42-mdk/build/libs/*.jar
