name: Java CI with Gradle

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: forge-1.16.5-36.2.42-mdk

    - name: Build with Gradle
      run: ./gradlew build --no-daemon
      working-directory: forge-1.16.5-36.2.42-mdk

    - name: Upload Mod Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Mod
        path: forge-1.16.5-36.2.42-mdk/build/libs/*.jar
        
